# Generated by Django 4.0.5 on 2022-07-18 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Entrada'), ('2', 'Saída')], max_length=1)),
                ('descricao', models.CharField(max_length=50)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('dt_lancamento', models.DateField(auto_now=True)),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pessoas.pessoas')),
            ],
            options={
                'db_table': 'Caixa',
            },
        ),
    ]
