# Generated by Django 4.0.4 on 2022-08-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='carga_horaria',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='vl_curso',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='periodo',
            field=models.IntegerField(choices=[(1, 'Matutino'), (2, 'Verpertino'), (3, 'Noturno')]),
        ),
    ]
