# Generated by Django 4.0.4 on 2022-07-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_completo', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('dt_nascimento', models.DateField(max_length=10)),
                ('celular', models.CharField(blank=True, max_length=15, unique=True)),
                ('fone_res', models.CharField(blank=True, max_length=14, unique=True)),
                ('nm_resp', models.CharField(blank=True, max_length=100)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=50)),
                ('perfil', models.CharField(choices=[(1, 'Aluno'), (2, 'Instrutor'), (3, 'Vendedor'), (4, 'Administrador')], max_length=1)),
                ('dt_alteracao', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Pessoas',
            },
        ),
    ]
