# Generated by Django 4.0.4 on 2022-08-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='perfil',
            field=models.CharField(choices=[(1, 'Aluno'), (2, 'Instrutor'), (3, 'Vendedor'), (4, 'Administrador')], max_length=50),
        ),
    ]
