# Generated by Django 4.0.4 on 2022-08-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoas', '0003_alter_pessoas_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='perfil',
            field=models.IntegerField(choices=[(1, 'Aluno'), (2, 'Instrutor'), (3, 'Vendedor'), (4, 'Administrador')]),
        ),
    ]
