# Generated by Django 4.0.4 on 2022-08-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoas', '0004_alter_pessoas_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='fone_res',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
